"""add description to classes

Revision ID: 66368f1a8ebb
Revises: 77e57888ba58
Create Date: 2026-05-02 21:53:29.250582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66368f1a8ebb'
down_revision = '77e57888ba58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
